name: 3.x (Retro-compatibility) Deployment Workflow
on:
  pull_request:
    branches:
      - 3.x
  push:
    branches:
      - 3.x

jobs:
  deps_safety_check:
    name: Check the safety of our dependencies.

    runs-on: "${{ matrix.os }}"

    strategy:
      fail-fast: false
      matrix:
        python_version:
          - "3.9"
        os:
          - ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        name: Clone repository

      - name: Set up Python ${{ matrix.python_version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python_version }}

      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          pip install safety

      - name: Check the safety of our dependencies.
        run: safety check

  deploy_dev_to_pypi:
    needs: [deps_safety_check]
    name: "Deploy 📦 to the PyPi"

    if: github.event_name == 'push' && github.ref == 'refs/heads/3.x'

    runs-on: "${{ matrix.os }}"

    strategy:
      fail-fast: false
      matrix:
        python_version:
          - "3.9"
        os:
          - ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        name: Clone repository

      - name: Set up Python ${{ matrix.python_version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python_version }}

      - name: Install dependencies
        run: |
          pip install twine wheel setuptools

      - name: Build 📦
        run: |
          python setup.py sdist bdist_wheel

      - name: Check 📦
        run: |
          twine check dist/*

      - name: Publish 📦 to PyPI
        uses: pypa/gh-action-pypi-publish@master
        with:
          password: ${{ secrets.PYPI_DEV_API_TOKEN }}
          skip_existing: true

  deploy_stable_to_pypi:
    needs: [deps_safety_check]
    name: "Deploy 📦 to the PyPi"

    if: github.event_name == 'push' && github.ref == 'refs/heads/master'

    runs-on: "${{ matrix.os }}"

    strategy:
      fail-fast: false
      matrix:
        python_version:
          - "3.9"
        os:
          - ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        name: Clone repository

      - name: Set up Python ${{ matrix.python_version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python_version }}

      - name: Install dependencies
        run: |
          pip install twine wheel setuptools

      - name: Build 📦
        run: |
          python setup.py sdist bdist_wheel

      - name: Check 📦
        run: |
          twine check dist/*

      - name: Publish 📦 to PyPI
        uses: pypa/gh-action-pypi-publish@master
        with:
          password: ${{ secrets.PYPI_API_TOKEN }}
          skip_existing: true

  deploy_to_docker_hub:
    needs: [deps_safety_check]
    name: "Deploy 📦 to the Docker Hub"

    if: github.event_name == 'push'

    runs-on: "${{ matrix.os }}"

    strategy:
      fail-fast: false
      matrix:
        python_version:
          - "3.9"
        os:
          - ubuntu-latest

    env:
      DOCKER_PYTHON_VERSION: "3.9"
      BUILDER_CLONE_DIRNAME: pyfunceble_docker
      OUR_DOCKER_USERNAME: ${{ secrets.OUR_DOCKER_USERNAME }}
      OUR_DOCKER_PASSWORD: ${{ secrets.OUR_DOCKER_PASSWORD }}
      OUR_DOCKER_EMAIL: ${{ secrets.OUR_DOCKER_EMAIL }}

    steps:
      - uses: actions/checkout@v2
        name: Clone repository

      - uses: actions/checkout@v2
        name: Clone docker 📦 repository
        with:
          repository: PyFunceble/docker
          path: ${{ env.BUILDER_CLONE_DIRNAME }}/

      - name: Set up Python ${{ matrix.python_version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python_version }}

      - name: Install dependencies
        run: |
          pip install ${{ env.BUILDER_CLONE_DIRNAME }}/.

      - name: Get version of builder
        run: |
          pyfunceble-docker-builder --version

      - name: Build, Check and Publish 📦
        run: >
          pyfunceble-docker-builder -b ${{ env.BUILDER_CLONE_DIRNAME }}/builder
          -p "$(python setup.py --name)"
          --pyfunceble-version="$(python setup.py --version)"
          --python-version="${DOCKER_PYTHON_VERSION}"
          --publish --commit="$(git log -1 --format=format:'%H')"
